services:
  db:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: procurement
    ports:
      - 5433:5432
    volumes:
      - procurement_db_data:/var/lib/postgresql/data

volumes:
  procurement_db_data:
